apiVersion: apps/v1
kind: Deployment
metadata:
  name: brkg-bad-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: brkg-bad
  template:
    metadata:
      labels:
        app: brkg-bad
    spec:
      containers:
        - name: brkg-bad
          image: yash5090/brkg-bad:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
